apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gxh6lwgi8-go 
  janus-idp.io/tekton: gxh6lwgi8-go
  backstage.io/kubernetes-id: gxh6lwgi8-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gxh6lwgi8-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  